// Types for image imports (`import icon from "./icon.png"`).
//
// Next normally brings these in through `next-env.d.ts`, but that file is
// generated by `next typegen` and git-ignored. CI runs `pnpm lint` before that
// step, and type-aware lint rules saw every image import as an error type.
// Referencing them from a committed file keeps lint independent of generated files.
/// <reference types="next/image-types/global" />
